
version: 2

models:
  - name: OBT_ECOM
    description: "unified data"
    columns:
      - name: id
        tests: 
          - dbt_expectations.expect_column_values_to_not_be_null:
              row_condition: "id is not null"
      - name: timestamp
        tests: 
          - dbt_expectations.expect_column_values_to_not_be_null:
              row_condition: "id is not null"
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp
      - name: product_name 
      - name: price
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: double
      - name: quantity
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: int64
      - name: category 
      - name: customer_name 
      - name: customer_age
        tests:
          - dbt_expectations.expect_column_min_to_be_between:
              min_value: 18 
      - name: email
      - name: address
      - name: country
      - name: payment_method
        tests:
        - dbt_expectations.expect_column_values_to_be_in_set:
            value_set: ['Credit Card', 'Cash', 'PayPal']
      - name: phone_number
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar
      - name: discount_applied
      - name: shipping_method
      - name: order_status
      

  - name: revenue
    description: "prep for dashboard"
    columns:
      - name: id
      - name: timestamp
      - name: product_name 
      - name: price
      - name: quantity
      - name: revenue
      - name: category 
      - name: customer_name 
      - name: customer_age
      - name: email
      - name: address
      - name: country
      - name: payment_method
      - name: phone_number
      - name: discount_applied
      - name: shipping_method
      - name: order_status

  - name: aggregates
    description: "aggregates for dashboard"
    columns:
      - name: order_year
      - name: order_month
      - name: total_orders
      - name: total_items_sold
      - name: total_revenue 
      - name: avg_price
      - name: max_revenue
      - name: min_revenue
      - name: avg_discount_applied 